### ISSUE TITLE
WebGLAnimation and WebGLInfo won't build on the master barnch

### ISSUE THREAD

**Issue by mprogram** [jupyter-widgets/pythreejs#204]
My build output with the examples corresponds to that of Travis. However, I'm getting the following non-fatal errors, each emitted twice, while actually trying to build the `master` branch:

`error creating wrapper:`
`Error: invalid class name: WebGLAnimation`
`.   at getExtraDefines (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:187:15)`
`.   at new JavascriptWrapper (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:330:34)`
`.   at createJavascriptWrapper (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:554:19)`
`.   at Glob.<anonymous> (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:261:26)`
`.   at emitOne (events.js:116:13)`
`.   at Glob.emit (events.js:211:7)`
`.   at Glob._emitMatch (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:489:8)`
`.   at Glob._processSimple2 (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:705:8)`
`.   at ~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:676:10`
`.   at Glob._stat2 (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:789:10)`
`skipping: renderers/webgl/WebGLAnimation.js`

and

`error creating wrapper:`
`Error: invalid class name: WebGLInfo`
`.   at getExtraDefines (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:187:15)`
`.   at new JavascriptWrapper (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:330:34)`
`.   at createJavascriptWrapper (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:554:19)`
`.   at Glob.<anonymous> (~/jupyter-widgets/pythreejs/js/scripts/generate-wrappers.js:261:26)`
`.   at emitOne (events.js:116:13)`
`.   at Glob.emit (events.js:211:7)`
`.   at Glob._emitMatch (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:489:8)`
`.   at Glob._processSimple2 (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:705:8)`
`.   at ~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:676:10)`
`.   at Glob._stat2 (~/jupyter-widgets/pythreejs/js/node_modules/glob/glob.js:789:10)`
`skipping: renderers/webgl/WebGLInfo.js`

Is is a known situation, and is it being tracked somewhere for further reference? Could it be safely ignored as for now?

BTW, three.js r94 has been released, and r95 is coming soon. Many thanks for keeping up with all your work!

**Comment by vidartf** [comment]
Thanks for the report! From what I can tell, you are trying to build against r93 or later, without having updated the config. I think these errors should be safe to ignore, as these classes should likely be ignored anyway (i.e. not used in pythreejs).

For now, updating the three.js version requires a full manual scan of the changelogs to look for any changes that will affect pythreejs. Then an appropriate release version will have to be decided on, as pythreejs follows semver, while threejs does not. While this is not too much work, it is still enough that pythreejs is unlikely to follow threejs super-closely by default. However, if there are specific new features that people want, a simple request for an update via an issue should help push it along!

**Comment by mprogram** [comment]
See also #206 for r95 unusual manifestation under JLab in incognito mode (!), but not under the classic notebook (checked simultaneously with restarting the kernels), whereas r90 is, factually, installed (double, cross-checked, file stamps are from 7 Jun).
