### ISSUE TITLE
Buggy extension install process

### ISSUE THREAD

**Issue by ataiya** [jupyter-widgets/pythreejs#266]
```
atagliasacchi@cpumini:~$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
Installing /home/atagliasacchi/.local/lib/python3.5/site-packages/pythreejs/static -> jupyter-threejs
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
```

and then try with sudo:

```
atagliasacchi@cpumini:~$ sudo jupyter nbextension install --py --symlink --sys-prefix pythreejs
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named 'pythreejs'
```

Solution? (feel this should be taken care by installation...?)
```
atagliasacchi@cpumini:~$ sudo chmod a+w /usr/share/jupyter/
atagliasacchi@cpumini:~$ jupyter nbextension install --py --symlink --sys-prefix pythreejs
Installing /home/atagliasacchi/.local/lib/python3.5/site-packages/pythreejs/static -> jupyter-threejs
Symlinking: /usr/share/jupyter/nbextensions/jupyter-threejs -> /home/atagliasacchi/.local/lib/python3.5/site-packages/pythreejs/static
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable pythreejs --py --sys-prefix
atagliasacchi@cpumini:~$ sudo chmod a-w /usr/share/jupyter/
```

And then the same thing again...
```
atagliasacchi@cpumini:~$ jupyter nbextension enable --py --sys-prefix pythreejs
Enabling notebook extension jupyter-threejs/extension...
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 386, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 386, in <listcomp>
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 136, in update
    self.set(section_name, data)
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 110, in set
    self.ensure_config_dir_exists()
  File "/usr/local/lib/python3.5/dist-packages/notebook/config_manager.py", line 67, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/etc'
```

Sigh.

**Comment by vidartf** [comment]
Depending on your setup, the different flags for the nbextension install are the right ones. The README uses the most common, but you might want to vary the `--sys-prefix` with e.g. `--user`, and you probably do not need the `--symlink` flag unless you plan on modifying the source of pythreejs. If you have an improvement for the install scripts, any PRs would be most welcome!

**Comment by vidartf** [comment]
Closing as answered
